### ISSUE TITLE
How to clang-format without modifying the file

### ISSUE THREAD

**Issue by RunDevelopment** [Galarius/vscode-opencl#16]
All other formatters in VSCode I use (e.g. JS-, JSON-, CSS-, XML-formatters) don't modify the input file, so you can make some changes to a file, format it, make some other changes, and only then save.
This is my usual behavior which doesn't work with this extension where you have to: make some changes, save, format, make some other changes, and then save. 

Not a huge issue but mildly annoying because I'm not used to it and because when I format without saving first, I get a nice conflict.

So, I wanted to ask if there is a way to configure the OpenCL formatter so that it behaves like other formatters.

**Comment by Galarius** [comment]
I need to update formatter provider for this.

**Comment by Galarius** [comment]
@RunDevelopment , I have updated formatter provider at [pre-release 0.6.2](https://github.com/Galarius/vscode-opencl/releases/tag/0.6.2-pre). It should fix both issues (#15 and #16). Could you try it out? I made a package [vscode-opencl-0.6.2.vsix](https://github.com/Galarius/vscode-opencl/releases/download/0.6.2-pre/vscode-opencl-0.6.2.vsix)

**Comment by RunDevelopment** [comment]
I would love to test it but it seems like I can't install it properly. I uninstalled v0.6.1 of the extension, restarted, installed the `.vsix` via the "Install from VSIX..." menu item. Restarted again.

When trying to format a document (`line2.cl`) VS Code just hits me with this:

![image](https://user-images.githubusercontent.com/20878432/74268408-1ffd6a00-4d08-11ea-84ad-dc867c632ea0.png)

I also noticed that the `opencl.formatting.options` setting isn't supported anymore.

![image](https://user-images.githubusercontent.com/20878432/74268620-74084e80-4d08-11ea-8d04-7103c73346ec.png)

**Comment by Galarius** [comment]
> When trying to format a document (line2.cl) VS Code just hits me with this:

Thanks for testing. It seems I didn't reload after installing .vsix package. 
I changed some properties in package.json and all providers were not included in .vsix file.

> I also noticed that the opencl.formatting.options setting isn't supported anymore.

That was the plan. Options were meant for other formatters but `clang-format` actually needs only configuration file. I dropped support for other formatters.

**Comment by RunDevelopment** [comment]
So asytle lost the race. Well, in my little bubble it seems like everybody uses clang-format anyway.

Btw. If you give the fixed `.vsix` I can also test the actual formatting ;)

**Comment by Galarius** [comment]
@RunDevelopment, [vscode-opencl-0.6.3.vsix](https://github.com/Galarius/vscode-opencl/releases/download/0.6.3-pre/vscode-opencl-0.6.3.vsix) is better :)

**Comment by RunDevelopment** [comment]
I installed your extension, reloaded and tested it. Here are the results: 

First I used my usual setting (custom clang-format) and it didn't work. This is the `Error: spawn "..." ...` message in the dev console.

Then I removed the custom formatter, so it uses the `clang-format` shipped with `ms-vscode.cpptools`. This didn't work just as expected because `ms-vscode.cpptools` ships with an older version of `clang-format` which doesn't support all the options I use. 
I got a nice error notification explaining the unsupported option, so no issue here. Working as intended.

Then I removed the unsupported option and everything works. The formatter now behaves nicely.

I did all three things after another, so the console has logs for all of them.
Here's a screenshot of VSCode's dev console. The extension did not output anything else.

![image](https://user-images.githubusercontent.com/20878432/74473211-810d7500-4ea3-11ea-981f-becc4bfdd76c.png)

---

So yeah. Formatting works but not for custom `clang-format`s. (I want to use `clang-format` v9.0.0 btw.)

Hopefully, I could provide enough information to fix the problem with custom formatters. If you want me to try out anything else, feel free to ask.

---

Also, it seems like you search for the `.clang-format` config file without considering parent directories. Mine is two directories up relative to the files I want to format.

```
[OpenCL Formatter] Configuration file '.clang-format' is not found at ...
```

**Comment by Galarius** [comment]
Thank you for the detailed description. 

As for searching for ‘.clang-format’ file, I pass kernel’s content directly to stdin. In this case clang-format can only get configuration file from the current directory (according to help). I will try to find a more convenient way.

**Comment by Galarius** [comment]
@RunDevelopment, I tried to reproduce that error with launching a newer `clang-format` from Visual Studio 2019, but was not able to get the error. However I updated the way I pass a file to formatter. It should fix the problem with searching for configuration file in file's parent directories. Hopefully it will also resolve the launching issue. 

[vscode-opencl-0.6.4.vsix](https://github.com/Galarius/vscode-opencl/releases/download/0.6.4-pre/vscode-opencl-0.6.4.vsix)

**Comment by RunDevelopment** [comment]
> I tried to reproduce that error with launching a newer clang-format from Visual Studio 2019, but was not able to get the error.

That's strange because I still get the error. I'll try it out on another machine.

![image](https://user-images.githubusercontent.com/20878432/74593967-52bda000-5031-11ea-9d98-14a15d5d9d48.png)

---

Also, with an incorrect `.clang-format` file (unsupported option in my case) and the `clang-format` from `ms-vscode.cpptools`, I get a warning and an error with the same message but not the actual details as to what went wrong. 
The `stderr` output should probably just be displayed as one error.

![image](https://user-images.githubusercontent.com/20878432/74594023-e4c5a880-5031-11ea-8c57-ae3cc220b297.png)

**Comment by RunDevelopment** [comment]
Yup. Same issue on my other machine.

![image](https://user-images.githubusercontent.com/20878432/74594152-72ee5e80-5033-11ea-8d84-61bc6c22d080.png)

**Comment by Galarius** [comment]
> That's strange because I still get the error. I'll try it out on another machine.

What happens if you run the command which is logged in dev console from the command line?

**Comment by RunDevelopment** [comment]
It just works.

```
C:\Users\micha>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\bin\clang-format.exe" -verbose -style=file -fallback-style=LLVM c:\Users\micha\source\repos\Claw\Claw.Examples\cl\line2.cl
Formatting c:\Users\micha\source\repos\Claw\Claw.Examples\cl\line2.cl

#ifndef LINE2_CL
#define LINE2_CL

struct __attribute__((packed)) line2 {
        float2 o;
        float2 d;
};

...
```

**Comment by Galarius** [comment]
Could you try to open your [sample.zip](https://github.com/Galarius/vscode-opencl/files/4113575/sample.zip) in vs code and run the formatter?

**Comment by RunDevelopment** [comment]
I found the problem. Because of the spaces in the path to `clang-format.exe`, I had to quote the path or else it wouldn't work with the previous version of this extension. Removing the quotes makes everything work. Node's `child_process` API seems to be unable to handle the quotes.

For backward compatibility, you should probably either remove the quotes or display an error notification.

**Comment by RunDevelopment** [comment]
@Galarius Found a bug.

If the file formatted is encoded as _UTF-8 with BOM_, a strange character (cp: 65279 (dec)) will be added at the beginning of the document. The code point of the character is 65279 (dec) or 0xFEFF which is the [BOM of UTF-8](https://en.wikipedia.org/wiki/Byte_order_mark).

---

Some good news: v0.6.4 resolves #15.

**Comment by Galarius** [comment]
It also fails with other encodings like CP 1251. 
In the previous version of the extension I used inplace formatting (flag `-i`) which handles encoding well. Now I receive stdout from `clang-format` in `utf8` encoding which breaks the content. Unfortunately I can not detect file's encoding using vscode api (There is a proposal issue already, but it is still opened).

**Comment by RunDevelopment** [comment]
I don't quite understand the issue. When [formatting](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#format-source-code-in-an-editor), aren't you given the JS UTF-16 string of the document via [`getText()`](https://code.visualstudio.com/api/references/vscode-api#TextDocument), so you don't have to deal with encodings? 
So from my understanding, you get the text (UTF-16), pass it to `clang-format`'s stdin (UTF-8), read `clang-format`'s stdout (UTF-8), and pass it back to VSCode (UTF-16) via a [TextEdit](https://code.visualstudio.com/api/references/vscode-api#TextEdit). I just don't see why the encoding of the file matters.

Also, there are libraries that can detect the encoding (e.g. [this one](https://www.npmjs.com/package/charset-detector)), so why not use those?

**Comment by Galarius** [comment]
Here is the catch. In the previous version I used stdin, but in this case `clang-format` can't get config file from parent directories. Now I pass a file name as an argument. It allows `clang-format` to find config file. However the result is passed to stdout which is `utf8` for `cp.spawn` by default.

> Also, there are libraries that can detect the encoding (e.g. this one), so why not use those?

I've tried [this one](https://www.npmjs.com/package/chardet). The correctness of detection is quite unreliable.

When I run the same formatting command manually in a terminal, I get damaged result as well (at least for Windows 1251 encoding).

**Comment by RunDevelopment** [comment]
Do you have a file where I can test this on?

> In the previous version I used stdin

So, what are you doing now then? I mean, you obviously can't you the file itself for dirty documents.

**Comment by Galarius** [comment]
> Do you have a file where I can test this on?

[kernel.cl.zip](https://github.com/Galarius/vscode-opencl/files/4209936/kernel.cl.zip)

The file is saved using Windows 1251 encoding with some Cyrillic symbols at the beginning. Running `clang-format -verbose -style="{UseTab: Never, IndentWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0}" kernel.cl` in macOS terminal will result into:

<details>
<summary>
stdout
</summary>
// ����

/* binary tree node definition */
typedef struct nodeStruct
{
    int value;
    __global struct nodeStruct *left;
    __global struct nodeStruct *right;
} node;

/* search keys */
typedef struct searchKeyStruct
{
    int key;
    __global node *oclNode;
    __global node *nativeNode;
} searchKey;

/***
* sample_kernel:
***/
__kernel void sample_kernel(__global void *bstRoot,
                            __global void *searchKeyVect)
{
    __global node *searchNode = (__global node *)(bstRoot);
    __global searchKey *keyPtr = (__global searchKey *)(searchKeyVect);
    int gid = get_global_id(0);
    __global searchKey *currKey = keyPtr + gid;

    while (NULL != searchNode)
    {
        if (currKey->key == searchNode->value)
        {
            /* rejoice on finding key */
            currKey->oclNode = searchNode;
            searchNode = NULL;
        }
        else if (currKey->key < searchNode->value)
        {
            /* move left */
            searchNode = searchNode->left;
        }
        else
        {
            /* move right */
            searchNode = searchNode->right;
        }
    }
}
</details>

It makes sense actually, considering terminal default locale. But working with encodings is always hard, especially in Windows. I agree it would be better to handle an independent buffer somehow. Need to research a bit more.

> So, what are you doing now then?

In the latest version I pass to `clang-format` document's file name as the latest argument and get an output to standard output.

**Comment by RunDevelopment** [comment]
I was a little confused but now I see how you implemented it (I didn't notice the branch before). And unfortunately, this won't work.

The problem are dirty files. You just let `clang-format` read the file as is right now, so I still have to save. I don't get conflicts anymore because the current version in the editor is discarded which isn't what I want. 
(Say you open a kernel, make some edits without saving and then format. All of the edits are discarded then.)

You said that stdin didn't work for you but on my side, the following implementation works for UTF-8 with and w/o BOM and the cp1251 file you gave me.

<details>

```ts
function runner(app: string, args: string[], document: TextDocument, token: CancellationToken): Promise<TextEdit[]> {
    console.log(`[OpenCL Formatter] Running ${app} with arguments: ${args}...`)
    return new Promise((resolve, reject) => {
        let stdout = ''
        let stderr = ''

        const cwd = path.dirname(document.fileName)
        const p = spawn(app, args, { cwd })

        token.onCancellationRequested(() => !p.killed && killTree(p.pid))

        p.stdout.setEncoding('utf8')
        p.stdout.on('data', (data) => (stdout += data))
        p.stderr.on('data', (data) => (stderr += data))

        p.on('error', err => {
            if (err)
                return reject(err)
        })

        p.on('close', code => {

            if (code !== 0) {
                console.error(`[OpenCL Formatter] Process finished with code ${code}`)
                return reject(stderr)
            }

            const fileStart = new vscode.Position(0, 0)
            const fileEnd = document.lineAt(document.lineCount - 1).range.end
            const textEdits = [
                new vscode.TextEdit(new vscode.Range(fileStart, fileEnd), stdout)
            ]
            return resolve(textEdits)
        })

        p.stdin.end(document.getText(), 'utf-8');
    })
}
```

</details>

**Comment by RunDevelopment** [comment]
Also, just curious:
You look for whether `.clang-format` exists because it's necessary for `getClangArgumentList`. But I don't really understand why `getClangArgumentList` has [this `if`](https://github.com/Galarius/vscode-opencl/blob/1387cfac65960f72d6623a4cf5ed47d843c038ca/src/providers/formatter/clang/formatter.js#L40). Can `-fallback-style` not be an YAML object?

Also, right now, you might return `-fallback-style=Visual Studio`, so I think a check is missing here.

**Comment by Galarius** [comment]
> The problem are dirty files. 

I see the problem. In that case using stdin is necessary.

> You said that stdin didn't work for you but on my side, the following implementation works for UTF-8 with and w/o BOM and the cp1251 file you gave me.

I will look into it once more. I've just found how to provide a path to configuration file when using stdin. Just need to add `-assume-filename=`.

**Comment by Galarius** [comment]
> Can -fallback-style not be an YAML object?

`-fallback-style='Visual Studio'` is invalid, so I needed to update `-style` argument

```
./clang-format -style='file' -fallback-style='Visual Studio' kernel.cl
Invalid fallback style "Visual Studio
```

**Comment by RunDevelopment** [comment]
> I've just found how to provide a path to configuration file when using stdin. Just need to add -assume-filename=.

The cwd alone will also work. Well, it does on my machine.

> -fallback-style='Visual Studio' is invalid

Yeah but very much possible with the current implementation.

---

To answer my own question: No, `-fallback-style` cannot be a YAML object.

```
C:\Users\micha\source\repos\Claw\Claw.Examples\cl>cat line2.cl | clang-format -fallback-style={}
Invalid fallback style "{}

C:\Users\micha\source\repos\Claw\Claw.Examples\cl>cat line2.cl | clang-format -fallback-style={Indent:4}
Invalid fallback style "{Indent:4}
```

**Comment by Galarius** [comment]
@RunDevelopment, I have implemented everything we discussed in the [release-0.6.5-pre](https://github.com/Galarius/vscode-opencl/releases/download/0.6.5-pre/vscode-opencl-0.6.5.vsix).

**Comment by RunDevelopment** [comment]
Works perfectly now! Thank you for your work!
BOM and cp1251 both work and #15 is fixed as well.

Really, thank you very much. This makes editing kernels a whole lot smoother!
